### ISSUE TITLE
Firefox Dev Ed. Inspector selector arrow fails with FireQuery enabled

### ISSUE THREAD

**Issue by CodaCodr** [firebug/firequery#25]
Like the title says. When FireQuery is enabled, the inspector's selector arrow tool does not highlight/find/locate the html in the main window.
Disable FireQuery and Inspector starts working properly again.

Firefox Developer Edition.
Windows 7.

**Comment by janodvarko** [comment]
What do you mean by "inspector selector arrow"?

Honza

**Comment by CodaCodr** [comment]
The tool in the inspector that lets you select the html element from the firefox window.  What do you call it? The tooltip says "Pick an element from the page".

**Comment by janodvarko** [comment]
Ah, I see what you mean. Not sure what the official name is, but I'd call it the element picker ;-)
I'll take a look at this tomorrow.

Thanks for the report!
Honza

**Comment by CodaCodr** [comment]
Ha - yeah, maybe - though an arrow is an arrow (not a pick) ;)

**Comment by janodvarko** [comment]
I can't reproduce the problem on my machine (Win 7, 64 bits)
I am using DevEdition 41
See the attached screenshots

Can you provide detailed instructions?
Like e.g. what page to load, where to click, in which order, etc.

I am not sure what could be different in our configs...

Honza

![firequery1](https://cloud.githubusercontent.com/assets/37785/8589315/2806ec22-2615-11e5-8469-0906d3f74b4d.png)

**Comment by CodaCodr** [comment]
Yep - it's intermittent. If I start a fresh Dev Ed, it fails. If I refresh the page (F5) it starts to work, eventually - didn't notice that yesterday.

You don't need detailed instructions Jan - your testing method is fine.  The only diff with my stuff, mine is a huge amount of HTML (asp.net app behind corp firewall - sorry).  I tried to test CNN.com but it crashes Dev Ed. :( (think it's an e10s issue but didn't follow the rabbit trail too far).

I'd vote to table this one, Jan... it may be something in the browser and not the plugin specifically.

**Comment by janodvarko** [comment]
I just released beta 4
https://github.com/firebug/firequery/releases

There is one bug fixed and it might be related to this reported problem
Let me know how it works for you now if you have tim to test.

Honza

**Comment by CodaCodr** [comment]
Sorry, Jan, it's the same.  Here's what I did...
Opened Dev Ed, got the latest update. Closed it and reopened it. Removed previous beta of firequery, downloaded the new one - beta 4.  Restarted Dev Ed.  

Ran the page, opened Inspector, used the picker (grin) Inspector does not scroll the HTML into view.
Disabled beta 4, same test, Inspector works.
Re-enabled beta 4, Inspector fails again.

This time, F5 is failing to make the problem go away (so far, anyway).

**Comment by janodvarko** [comment]
Thanks for the testing!

Here is yet another version. I fixed one thing and I would be again curious whether it helps.
http://softwareishard.com/temp/firequery/firequery-2.0.0-beta.4.issue25.xpi

(if this doesn't help it would be great to have a 'screen-share' meeting)

Honza

**Comment by CodaCodr** [comment]
Damn... I really thought you had it nailed.  I started with a fairly complex page where firequery was failing before, and it worked. When I navigated to a much more complex page, same issue "dead" inspector picker.

**Comment by janodvarko** [comment]
Forgot to ask, did you have e10s (multi-process) enabled/disabled?

Preferences > General > Enable multi-process Firefox Developer Edition

Honza

**Comment by CodaCodr** [comment]
yes - it was enabled. When it's disabled, the bug is still present.

**Comment by jeffgca** [comment]
@janodvarko I think I ran into this today. I was using the inspector to test the new hover feature and it got into a state where the markupview died and the console kept producing tons of these messages:

13:21:49.551 Error sending event: data-modified1 protocol.js:884

as well as the occasional traceback:

13:21:15.859 TypeError: markupView is null
Stack trace:
InspectorOverlay<.onDataModified@resource://gre/modules/commonjs/toolkit/loader.js -> resource://firequery-at-binaryage-dot-com/lib/inspector-overlay.js:295:9
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
Front<.onPacket@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/protocol.js:1201:1
DebuggerClient.prototype.onPacket@resource://gre/modules/devtools/dbg-client.jsm:977:7
LocalDebuggerTransport.prototype.send/<@resource://gre/modules/devtools/dbg-client.jsm -> resource://gre/modules/devtools/transport/transport.js:569:11
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:83:14
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:83:14
1 core.js:106

**Comment by janodvarko** [comment]
@canuckistani  what version of FireQuery do you use?

Update: are you using e10s?

Honza

**Comment by janodvarko** [comment]
FireQuery 2 beta 6 released 
(it could help to solve this issue or at least confirm that the effort goes in the right direction)

https://github.com/firebug/firequery/releases

Honza

**Comment by janodvarko** [comment]
There is a new version (beta 7)
https://github.com/firebug/firequery/releases/tag/firequery-2.0.0-beta.7

There is another fix that could help to solve this issue.

Honza
